apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-ingress
  namespace: blog-prod
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # Sans cela le chat ne récupère pas les messages
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://blog.devopsnotes.org"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/websocket-services: "blog-service"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  tls:
  - hosts:
    - blog.devopsnotes.org
    secretName: blog-devopsnotes-tls
  rules:
  - host: blog.devopsnotes.org
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: blog-service
            port:
              number: 5000
      - path: /socket.io
        pathType: ImplementationSpecific
        backend:
          service:
            name: blog-service
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blog-service
            port:
              number: 80
