apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-devopsnotes-deployment
  namespace: blog-prod
  labels:
    app: blog-devopsnotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-devopsnotes
  template:
    metadata:
      labels:
        app: blog-devopsnotes
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
      - name: blog-backend
        image: registry.gitlab.com/portfolio-kamal-guidadou/devopsnotes-blog/backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DEBUG
          value: "app:*"
        envFrom:
        - secretRef:
            # S'assurer que le secret a bien été créé dans le namespace blog-prod
            name: blog-secrets
      - name: blog-frontend
        # Utilisation de la variable GitLab CI pour l'image frontend
        image: registry.gitlab.com/portfolio-kamal-guidadou/devopsnotes-blog/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80