apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: blog-prod
spec:
  selector:
    app: blog-devopsnotes
  ports:
    - protocol: TCP
      port: 80         # Port exposé par le service
      targetPort: 80   # Port sur lequel Nginx écoute dans le pod
